# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/Jacksgong"
  #weibo: "#"
  rss: "/atom.xml"
  zhihu: "http://www.zhihu.com/people/jacks-gong"
  #douban: "#"
  #mail: "igzhenjie@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "https://cn.linkedin.com/in/jacksgong"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: false

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: http://7xjww9.com1.z0.glb.clouddn.com/avatar_h.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
duoshuo: "jacksgong"
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
#  卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我一定要过一段无怨无悔的人生，将来一定要有所建树，自由自在的活着，比谁都要自由。